educate_portal/urls.py
from django.urls import path
from .import views

app_name = 'educate_portal'
urlpatterns = [
    path('', views.StandardListView.as_view(), name='standard_list'),
    path('<slug:slug>/', views.SubjectListView.as_view(), name='subject_list'),
    path('<str:standard>/<slug:slug>/',
         views.LessonListView.as_view(), name='lesson_list'),
    path('<str:standard>/<str:slug>/create/',
         views.LessonCreateView.as_view(), name='lesson_create'),
    path('<str:standard>/<str:subject>/<slug:slug>/',
         views.LessonDetailView.as_view(), name='lesson_detail'),
    path('<str:standard>/<str:subject>/<slug:slug>/update/',
         views.LessonUpdateView.as_view(), name='lesson_update'),
    path('<str:standard>/<str:subject>/<slug:slug>/delete/',
         views.LessonDeleteView.as_view(), name='lesson_delete'),
          # path('become_teacher/', views.become_teacher, name='become_teacher'),
]

teaching_blog/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.urls import path
from django.conf.urls import include

urlpatterns = [
    path('', include('users_app.urls')),
    path('educate_portal/', include('educate_portal.urls')),
    path('admin/', admin.site.urls),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

users_app/urls.py
from django.urls import path
from users_app import views


# app_name = 'users_app'
urlpatterns = [
    path('', views.HomeView.as_view(), name='index'),
    path('register/', views.register, name='register'),
    path('user_login/', views.user_login, name='user_login'),
    path('logout/', views.user_logout, name='user_logout'),
    path('profileEd/', views.profile_editor, name='profile_editor'),

]

educate_portal/models.py
from django.utils import timezone
from django.db import models
import random
from django.urls import reverse
from django.contrib.auth.models import User
import os


class Standard(models.Model):
    name = models.CharField(max_length=100, unique=True,verbose_name="Заголовок категории")
    slug = models.SlugField(null=True, blank=True,verbose_name="Название в адресной строке")
    description = models.TextField(max_length=500, blank=True,verbose_name="Описание")

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Предмет обучения'
        verbose_name_plural = 'Предмет обучения'


def save_subject_image(instance, filename):
    upload_to = 'Images/'
    ext = filename.split('.')[-1]
    # get filename
    if instance.subject_id:
        filename = 'Subject_Pictures/{}.{}'.format(instance.subject_id, ext)
    return os.path.join(upload_to, filename)


class Subject(models.Model):
    subject_id = models.CharField(max_length=100, unique=True,verbose_name="айди подкатегории")
    name = models.CharField(max_length=100,verbose_name="название")
    slug = models.SlugField(null=True, blank=True,verbose_name="подкатегория в адресной строке")
    standard = models.ForeignKey(
        Standard, on_delete=models.CASCADE, related_name='subjects')
    image = models.ImageField(
        upload_to=save_subject_image, blank=True, verbose_name='Изображение подкатегории')
    description = models.TextField(max_length=500, blank=True,verbose_name="Описание подкатегории")

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Категория предмета обучения'
        verbose_name_plural = 'Категория предмета обучения'


def save_lesson_files(instance, filename):
    upload_to = 'Images/'
    ext = filename.split('.')[-1]
    # get filename
    if instance.lesson_id:
        filename = 'lesson_files/{}/{}.{}'.format(
            ext)
        if os.path.exists(filename):
            new_name = str(instance.name) + str('1')
            filename = 'lesson_images/{}/{}.{}'.format(
                instance.name, new_name, ext)
    return os.path.join(upload_to, filename)


class Lesson(models.Model):

    Standard = models.ForeignKey(Standard, on_delete=models.CASCADE)
    created_by = models.ForeignKey(User, on_delete=models.CASCADE,verbose_name="автор урока")
    created_at = models.DateTimeField(auto_now_add=True,verbose_name="дата создания")
    subject = models.ForeignKey(
        Subject, on_delete=models.CASCADE, related_name='lessons')
    name = models.CharField(max_length=250, verbose_name="Заголовок урока")
    description = models.TextField(
        max_length=5000, blank=True, verbose_name="Описание урока")
    description2 = models.TextField(
        max_length=5000, blank=True, verbose_name="Продолжение описания")
    position = models.PositiveSmallIntegerField(verbose_name="Номер урока")
    slug = models.SlugField(
        null=True, blank=True, verbose_name='уникальное поле в адресной строке (eng раскладка)')


    file = models.FileField(upload_to='videos/', null=True, blank=True,verbose_name="видео")

    ppt = models.FileField(upload_to=save_lesson_files,
                        blank=True,verbose_name="презентация(необязательное поле)")
    Notes = models.FileField(upload_to=save_lesson_files,
                             blank=True,verbose_name="урок в виде ворда/пдф(необязательное поле)")
    console = models.URLField(
        max_length=250, default='',verbose_name="возможность писать код, взяли с trinket io")

    class Meta:
        ordering = ['position']

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('educate_portal:lesson_list', kwargs={'slug': self.subject.slug, 'standard': self.Standard.slug})

    class Meta:
        verbose_name = 'Уроки'
        verbose_name_plural = 'Уроки'


class Comment(models.Model):
    lesson_name = models.ForeignKey(
        Lesson, null=True, on_delete=models.CASCADE, related_name='comments')
    comm_name = models.CharField(max_length=100, blank=True)

    author = models.ForeignKey(User, on_delete=models.CASCADE)
    body = models.TextField(max_length=500)
    date_added = models.DateTimeField(auto_now_add=True)

    def save(self, *args, **kwargs):
        self.comm_name = (
            "комментарий от" + "-" + str(self.author) + str(self.date_added))
        super().save(*args, **kwargs)

    def __str__(self):
        return self.comm_name

    class Meta:
        ordering = ['-date_added']

    class Meta:
        verbose_name = 'комментарии'
        verbose_name_plural = 'комментарии'


class Reply(models.Model):
    comment_name = models.ForeignKey(
        Comment, on_delete=models.CASCADE, related_name='replies')
    reply_body = models.TextField(
        max_length=500, verbose_name='ответ на комментарий')
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return "Ответ на комментарий " + str(self.comment_name.comm_name)

    class Meta:
        verbose_name = 'Ответы на комментарии'
        verbose_name_plural = 'Ответы на комментарии'
# Create your models here.

educate_portal/forms.py
from django import forms
from django.forms import ModelForm
from .models import Comment, Reply, Lesson


class LessonForm(forms.ModelForm):
    class Meta:
        model = Lesson
        fields = ('name', 'position', 'slug', 'description','file',
                  'description2', 'file', 'ppt', 'Notes')


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('body',)

        labels = {"body": "Комментарий:"}

        widgets = {
            'body': forms.Textarea(attrs={'class': 'form-control', 'rows': 4, 'cols': 70, 'placeholder': "Ваш комментарий"}),
        }


class ReplyForm(forms.ModelForm):
    class Meta:
        model = Reply
        fields = ('reply_body',)

        widgets = {
            'reply_body': forms.Textarea(attrs={'class': 'form-control', 'rows': 2, 'cols': 10}),
        }

    def __init__(self, *args, **kwargs):
        self.request = kwargs.pop('request', None)
        super(ReplyForm, self).__init__(*args, **kwargs)

educate_portal/views.py
from django.shortcuts import render, redirect
from django.views.generic import (TemplateView, DetailView,
                                  ListView, CreateView,
                                  UpdateView, DeleteView, FormView,)


from .models import Standard, Subject, Lesson
from django.urls import reverse_lazy
from .forms import CommentForm, ReplyForm, LessonForm
from django.http import HttpResponseRedirect
# фишки

from django.contrib.auth.decorators import login_required



class StandardListView(ListView):
    context_object_name = 'standards'
    model = Standard
    template_name = 'educate_portal/standard_list_view.html'


class SubjectListView(DetailView):
    context_object_name = 'standards'

    model = Standard
    template_name = 'educate_portal/subject_list_view.html'


class LessonListView(DetailView):
    context_object_name = 'subjects'
    model = Subject
    template_name = 'educate_portal/lesson_list_view.html'


class LessonDetailView(DetailView, FormView):
    context_object_name = 'lessons'
    model = Lesson
    template_name = 'educate_portal/lesson_detail_view.html'
    form_class = CommentForm
    second_form_class = ReplyForm

    def get_context_data(self, **kwargs):
        context = super(LessonDetailView, self).get_context_data(**kwargs)
        if 'form' not in context:
            context['form'] = self.form_class(request=self.request)
        if 'form2' not in context:
            context['form2'] = self.second_form_class(request=self.request)

        return context

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        if 'form' in request.POST:
            form_class = self.get_form_class()
            form_name = 'form'
        else:
            form_class = self.second_form_class
            form_name = 'form2'

        form = self.get_form(form_class)

        if form_name == 'form' and form.is_valid():
            print("comment form is returned")
            return self.form_valid(form)
        elif form_name == 'form2' and form.is_valid():
            print("reply form is returned")
            return self.form2_valid(form)

    def get_success_url(self):
        self.object = self.get_object()
        standard = self.object.Standard
        subject = self.object.subject
        return reverse_lazy('educate_portal:lesson_detail', kwargs={'standard': standard.slug,
                                                                    'subject': subject.slug,
                                                                    'slug': self.object.slug})

    def form_valid(self, form):
        self.object = self.get_object()
        fm = form.save(commit=False)
        fm.author = self.request.user
        fm.lesson_name = self.object.comments.name
        fm.lesson_name_id = self.object.id
        fm.save()
        return HttpResponseRedirect(self.get_success_url())

    def form2_valid(self, form):
        self.object = self.get_object()
        fm = form.save(commit=False)
        fm.author = self.request.user
        fm.comment_name_id = self.request.POST.get('comment.id')
        fm.save()
        return HttpResponseRedirect(self.get_success_url())


from django.contrib import messages

class LessonCreateView(CreateView):

    form_class = LessonForm
    context_object_name = 'subject'
    model = Subject
    template_name = 'educate_portal/lesson_create.html'

    def get_success_url(self):
        self.object = self.get_object()
        standard = self.object.standard
        return reverse_lazy('educate_portal:lesson_list', kwargs={'standard': standard.slug,
                                                                  'slug': self.object.slug})

    def form_valid(self, form, *args, **kwargs):
        self.object = self.get_object()
        fm = form.save(commit=False)
        fm.created_by = self.request.user
        fm.Standard = self.object.standard
        fm.subject = self.object
        fm.save()
        return HttpResponseRedirect(self.get_success_url())


class LessonUpdateView(UpdateView):
    fields = ('name', 'position', 'description',
              'description2', 'file', 'ppt', 'Notes')
    model = Lesson
    template_name = 'educate_portal/lesson_update.html'
    context_object_name = 'lessons'


class LessonDeleteView(DeleteView):
    model = Lesson
    context_object_name = 'lessons'
    template_name = 'educate_portal/lesson_delete.html'

    def get_success_url(self):
        print(self.object)
        standard = self.object.Standard
        subject = self.object.subject
        return reverse_lazy('educate_portal:lesson_list', kwargs={'standard': standard.slug, 'slug': subject.slug})

from django.shortcuts import render, redirect

# def become_teacher(request):
#     if request.method == 'POST' and 'become_teacher' in request.POST:
#         user_profile = request.user.profile
#         user_profile.is_teacher = True
#         user_profile.save()
#         return redirect('educate_portal:lesson_list')

#     # Handle the case where the form is not submitted
#     return render(request, 'lesson_list.html')

templates/educate_portal/lesson_delete.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block title %}Удаление урока {% endblock %}

{% block image_block %}
<style>
  #page-intro{
    background-image: url({% static "img/backg.jpg" %});
  }
.breadcrumb li{
margin-right: 5 px;
padding: 10px;
}


</style>
<header class="info-header">
  <div id="page-intro" class="container-fluid d-flex align-items-center justify-content-center ">
    <div class="row d-flex justify-content-center text-center">
      <div class="col-md-12 text-white">
        <!-- heading -->
        <h2 class="display-4 font-weight-bold  p-5 " style="color:white" > Удаление урока </h2>
        <div class="row d-flex justify-content-center text-center">
          <ul class="breadcrumb">
            <li><a href="{% url 'index' %}">Home</a></li>
            <li><a href="{% url 'educate_portal:standard_list' %}">Образовательный портал</a></li>
            <li><a href="{% url 'educate_portal:subject_list' slug=lessons.Standard.slug %}">{{lessons.Standard.name}}</a></li>
            <li><a href="{% url 'educate_portal:lesson_list' standard=lessons.Standard.slug slug=lessons.subject.slug %}">{{lessons.subject.name}}</a></li>
            <li><a href="{% url 'educate_portal:lesson_detail' standard=lessons.Standard.slug subject=lessons.subject.slug slug=lessons.slug %}">{{lessons.name}}</a></li>
            <li class="text-danger" >Удаление урока</li>
          </ul>
        </div>

        <!-- divider -->
        <hr style="color:#ff5722;">

        <!-- description -->
        <h4 class="white-text my-4">Если вы считаете что урок недостаточно подготовлен к обучению, то его всегда можно удалить!</h4>
  </div>
</header>
{% endblock %}



{% block content %}

<section id="best-features" class="text-center">
              <h2 class="mb-5 font-weight-bold" style="color:rgb(158, 8, 228)">Удалить {{lessons.name}}</h2>
              <!-- class row for description-->
              <div class="row d-flex justify-content-center mb-4">
                <!-- class column -->
                <div class="col-md-8">
                  <p class="grey-text"> При удалении урока мы не сможем его восстановить, будьте внимательны!</p>
                </div>
              </div>
</section>

 

<form method="post" class=''>
  
  {% csrf_token %}
  <section class="jumbotron text-center">
    <div class="container">
      <h1 class="jumbotron-heading">Вы уверены что хотите удалить урок {{lessons.name}} ?</h1>
      <p class="lead text-muted"> </p>
      <p>
         
        <input type="submit" value="Удалить" class="btn btn-danger btn-block">
        <a href="{% url 'educate_portal:lesson_detail' standard=lessons.Standard.slug subject=lessons.subject.slug slug=lessons.slug %}" class="btn btn-primary btn-block">отменить</a>
      </p>
    </div>
  </section>
</form>

{% endblock %}

templates/educate_portal/lesson_detail_view.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block title %} урок {{lessons.name}} {% endblock %}

{% block image_block %}
<style>
  #page-intro{
    background-image: url({% static "img/backg.jpg" %}) ;
  }

  .breadcrumb a{
margin-right: 5 px;
padding: 10px;
  }
</style>

<header class="info-header">
  <div id="page-intro" class="container-fluid d-flex align-items-center justify-content-center ">
    <div class="row d-flex justify-content-center text-center">
      <div class="col-12 text-white">
   
        <h2 class="display-4 font-weight-bold  p-5 " style="color: white" >  {{lessons.name}}</h2>
        <div class="row d-flex justify-content-center text-center">
          <ul class="breadcrumb">
            <li><a  href="{% url 'index' %}">Главная </a></li>
            <li><a  href="{% url 'educate_portal:standard_list' %}">Образовательный портал </a></li>
            <li><a  href="{% url 'educate_portal:subject_list' slug=lessons.Standard.slug %}">{{lessons.Standard.name}}</a></li>
            <li><a  href="{% url 'educate_portal:lesson_list' standard=lessons.Standard.slug slug=lessons.subject.slug %}">{{lessons.subject.name}}</a></li>
            <li class="text-danger" >{{lessons.name}}</li>
          </ul>
        </div>

 
        <hr style="color: rgb(158, 8, 228)">

  
        <h4 class="white-text my-4">В каждом уроке доступно видео для просмотра и полезный материал, который вы можете скачать!</h4>
  </div>
</header>
{% endblock %}

{% block content %}

<section class="text-center mr-3 ml-3">
    <h2 class="mb-0 mt-5 font-weight-bold" style="color: rgb(158, 8, 228)">Страница урока</h2>
    <div class="row d-flex justify-content-center mb-3">
       
        <h2 class="mb-0 mt-5 font-weight-bold">Урок добавлен {{lessons.created_at}} пользователем <cite title="Source Title">{{lessons.created_by}}</cite></h2>
      
    </div>
    <!-- video -->
    <div id ='a2'class="row d-flex justify-content-center mb-3 mr-3 ml-3">
    
         
      <video width="700" height="700" controls>
        <source src="{{ lessons.file.url }}" type="video/mp4">
       
    </video>
              
    </div>


{% if lessons.console %}
<h2 class="mb-0 mt-5 font-weight-bold" style="color: rgb(158, 8, 228)">Пишите код прямо в браузере! </h2>
<br>
 
<iframe width="100%" height="356" frameborder="0" marginwidth="0" marginheight="0" allowfullscreen src="{{lessons.console}}">
</iframe>
{% else %}
<br>
{% endif %}  
 
 

    <!-- download cards -->
    <div class="row d-flex justify-content-center mb-3 mt-3">
      <!-- download presentations -->
                {% comment %} <div class="col-md-3 mb-4 mt-4 mr-1 ml-1">
                  <div class="card box-shadow-hover">
                    <div class="card-body">
                      <h5 class="card-title">Скачать презентацию урока</h5>
                      {% if lessons.ppt %}
         
                      <a href="{{lessons.ppt.url}}" download>
                      <button type="button" class="button-les"><span>Скачать файл</span></button>
                      </a>
                      {% else %}
                      <p class="card-text" > нет презентации</p>
                      {% endif %}

                    </div>
                  </div>
                </div> {% endcomment %}
      <!-- download notes -->
                <div class="col-md-3 mb-4 mt-4 mr-1 ml-1">
                  <div class="card box-shadow-hover">
                    <div class="card-body">
                      <h5 class="card-title">Скачать файл урока</h5>
                      
                      {% if lessons.Notes %}
 
                      <a href="{{lessons.Notes.url}}" download>
                      <button type="button" class="button-les"><span>Скачать файл</span></button>
                      </a>
                       
                      {% else %}
                      <p class="card-text">Урок не был загружен</p>
                      {%endif%}

                    </div>
                  </div>
                </div>



                <div class="col-md-3 mb-4 mt-4 mr-1 ml-1">
                  <div class="card box-shadow-hover">
                    <div class="card-body">
                      <h5 class="card-title">Читать теорию и задания</h5>
                      
                      {% if lessons.Notes %}
                    
                      <a href=" {% get_media_prefix %}{{ lessons.Notes}}" target="_blank"> 
                      <button  type="button" class="button-les"> Читать урок 
                        
                        </button>
                      </a>
                       
                      {% else %}
                      <p class="card-text">К сожалению материала нет(((</p>
                      {%endif%}

                    </div>
                  </div>
                </div>
 
                 
    </div>
    <!-- update and delete button -->
    <div class="row d-flex justify-content-center mb-3 mt-3 mr-3 ml-3">
        {% if user.userprofileinfo.user_type == 'teacher' or user.is_superuser %}
        <div class="col-md-3 mb-3 text-center">
            <a href="{% url 'educate_portal:lesson_update' standard=lessons.Standard.slug subject=lessons.subject.slug slug=lessons.slug %}" class="btn btn-info btn-lg mr-4 btn-block">Обновить информацию урока</a>
        </div>
        <div class="col-md-3">
            <a href="{% url 'educate_portal:lesson_delete' standard=lessons.Standard.slug subject=lessons.subject.slug slug=lessons.slug %}" class="btn btn-danger btn-lg mr-4 btn-block"> Удалить урок </a>
        </div>
        {% endif %}
      </div>
</section>

<hr class="my-5" style="color: rgb(158, 8, 228)";>

<!-- Comments section -->
<section>
     
    <div class="container row">
      <div class="col-md-6 center container">
                              

      </div>
    </div>

    <section class="jumbotron ">
      
      <div class="container-left">
        <h2 class="mb-4 mt-5 font-weight-bold text-center" style="color: rgb(158, 8, 228)";>Имеются вопросы по уроку или возникла какая-то сложность?</h2>
    <h4 class="mt-2 font-weight-bold text-center" 
    style="color:  rgb(158, 8, 228)";>Тогда напишите свое мнение и мы вам ответим!</h4>
    <br><br>
        <form method="post">
          <div class="form-group ">
          {% csrf_token %}
          {{form|crispy}}
          
          <input type="submit" name="form" value="Оставить комментарий" class="btn btn-primary btn-md">
        
          </div>
    </form>
      </div>
    </section>

    

    <div class="row">
      {% for comment in lessons.comments.all %}
      <div class="col-12 mt-2 mb-2">
                      <div class="media border p-3">
                          <img src="{{comment.author.profile.profile_pic.url|default_if_none:'None'}}" alt="John Doe" class="mr-3 mt-3 rounded-circle" style="width:60px;">
                          <div class="media-body">
                                    <h4>{{comment.author}} <small><i>Дата комментария {{comment.date_added}}</i></small></h4>
                                    <p>{{comment.body}}</p>
                            {% for reply in comment.replies.all %}
                                        <div class="media p-3">
                                                <img src="{{reply.author.profile.profile_pic.url|default_if_none:'None'}}" alt="" class="mr-3 mt-3 rounded-circle" style="width:45px;">
                                        <div class="media-body">
                                                <h5>{{reply.author}} <small><i>Дата комментария {{reply.date_added}}</i></small></h5>
                                                <p>{{reply.reply_body}}</p>
                                          </div>
                                        </div>
                            {% endfor %}
                            <!-- form to post reply -->

                            

                            <form method="post">
                                  <input type="hidden" name="comment.id" value="{{comment.id}}">
                                  <input type="hidden" name="comment.comm_name" value="{{comment.comm_name}}">
                                  {% csrf_token %}
                                  {{form2.as_p}}
                                  <input type="submit" name="form2" value="Ответить" class="btn btn-info btn-md">
                            </form>
                          </div>
                  </div>
      </div>
      {% endfor %}
    </div>


</section>

{%endblock%}

templates/educate_portal/lesson_list_view.html
{% extends 'base.html' %}
{% load static %}
{% block title %} {{subjects.name}} {% endblock %}

{% block image_block %}
<style>
.breadcrumb li{
margin-right: 5px;
padding: 10px;
}
#page-intro{
  background-image: url({% static "img/backg.jpg" %});
}

</style>
<header class="info-header">
  <div id="page-intro" class="container-fluid d-flex align-items-center justify-content-center ">
    <div class="row d-flex justify-content-center text-center">
      <div class="col-md-10 text-white">
        <!-- heading -->
        <h2 class="display-4 font-weight-bold  p-5 " style="color:white" > {{subjects.name}} </h2>
        <div class="row d-flex justify-content-center text-center">
          <ul class="breadcrumb">
            <li><a href="{% url 'index' %}">Главная</a></li>
            <li><a href="{% url 'educate_portal:standard_list' %}">Образовательный портал</a></li>
            <li><a href="{% url 'educate_portal:subject_list' slug=subjects.standard.slug %}">{{subjects.standard}}</a></li>
            <li class="text-danger" >{{subjects.name}}</li>
          </ul>
        </div>

        <!-- divider -->
        <hr style="color:rgb(158, 8, 228)">

        <!-- description -->
        <h4 class="white-text my-4">Все доступные уроки данного раздела, советуем начинать с 1 урока каждого раздела, делитесь своим мнением и занимайтесь!</h4>
  </div>
</header>
{% endblock %}


{% block content %}
<section id="best-features" class="text-center">
              <h2 class="mb-5 mt-5 font-weight-bold" style="color:rgb(158, 8, 228)">Практикуйтесь, изучайте, создавайте!</h2>
              <!-- class row for description-->
              <div class="row d-flex justify-content-center mb-4">
                <!-- class column -->
                <div class="col-md-8 mb-5">
                  <p class="grey-text">Все доступные уроки раздела.</p>
                </div>
              </div>
              <!-- class row2 for cards -->
              <div class="row d-flex justify-content-center mb-3 mr-3 ml-3">
                {% for lesson in subjects.lessons.all %}
                <div class="col-sm-6 mb-4">
                  <div class="card box-shadow-hover">
                    <div class="card-body">
                      <h5 class="card-title">  {{lesson.name}}</h5>
                      <!-- <p class="card-text">With supporting text below as a natural lead-in to additional content.</p> -->
                      <a href="{% url 'educate_portal:lesson_detail' slug=lesson.slug subject=subjects.slug standard=lesson.Standard.slug %}" >
                      <button style="border-color: rgb(158, 8, 228); background-color: rgb(158, 8, 228); color: white; height: 50px;width: 150px;" type="button" class="button-les"><span>Изучать</span></button>
                      </a>
                    </div>
                  </div>
                </div>
                {% endfor %}
              </div>
              {% if user.is_authenticated %}
              <a href="{% url 'educate_portal:lesson_create' standard=subjects.standard.slug slug=subjects.slug %}"><button type="button" class="btn btn-success btn-lg btn-bloc" style="display: flex;margin: auto; margin-bottom: 20px;"> Добавить новый урок </button> </a>
              {% endif %}
 
          
        </div>

</section>






{%endblock%}

templates/educate_portal/lesson_update.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block title %}Обновление урока {% endblock %}

{% block image_block %}

<header class="info-header">
  <div id="page-intro" class="container-fluid d-flex align-items-center justify-content-center ">
    <div class="row d-flex justify-content-center text-center">
      <div class="col-md-10 text-white">
        <!-- heading -->
        <h2 class="display-4 font-weight-bold  p-5 " style="color:#ff5722;" > Обновление урока </h2>
        <div class="row d-flex justify-content-center text-center">
          <ul class="breadcrumb">
            <li><a href="{% url 'index' %}">Главная</a></li>
            <li><a href="{% url 'educate_portal:standard_list' %}">образовательный портал</a></li>
            <li><a href="{% url 'educate_portal:subject_list' slug=lessons.Standard.slug %}">{{lessons.Standard.name}}</a></li>
            <li><a href="{% url 'educate_portal:lesson_list' standard=lessons.Standard.slug slug=lessons.subject.slug %}">{{lessons.subject.name}}</a></li>
            <li><a href="{% url 'educate_portal:lesson_detail' standard=lessons.Standard.slug subject=lessons.subject.slug slug=lessons.slug %}">{{lessons.name}}</a></li>
            <li class="text-danger" >Обновление урока</li>
          </ul>
        </div>

        <!-- divider -->
        <hr style="color:#ff5722;">

        <!-- description -->
        <h4 class="white-text my-4">Здесь вы можете обновить и дополнить урок</h4>
  </div>
</header>
{% endblock %}


{% block content %}

<section id="best-features" class="text-center">
              <h2 class="mb-5 font-weight-bold" style="color:#ff5722;">Обновить урок {{lessons.name}}</h2>
              <!-- class row for description-->
              <div class="row d-flex justify-content-center mb-4">
                <!-- class column -->
                <div class="col-md-8">
                  <p class="grey-text">Заполните все поля и подтвердите обновление урока!</p>
                </div>
              </div>
</section>

<section class="jumbotron ">
  <div class="container">
<form method="post" enctype="multipart/form-data" class='text-start'>
  {% csrf_token %}
  {{form|crispy}}
  <div class="row">
        <div class="col-md-4 mb-3 mr-3">
                <input type="submit" value="Обновить урок" class="btn btn-info btn-block">
        </div>
        <div class="col-md-4 mb-3 mr-3">
                <a href="{% url 'educate_portal:lesson_detail' standard=lessons.Standard.slug subject=lessons.subject.slug slug=lessons.slug %}" class="btn btn-warning btn-block">Отменить изменения</a>
        </div>
</div>
</form>
</div>
</section>

{% endblock %}